import * as fs from 'fs'
import * as core from '@actions/core'
import {CandidateSearchResults} from './types'

export async function writeTable(
  outputPath: string,
  results: CandidateSearchResults[],
  whatIf?: boolean
): Promise<void> {
  // Write a new file each time
  if (!whatIf && fs.existsSync(outputPath)) {
    fs.unlinkSync(outputPath)
  }

  let fileContents =
    '| Extension | Total Hits | Unique Repositories |\n' +
    '| --- | --- | --- |\n'

  for (const result of results) {
    for (const extensionResult of result.extensionResults) {
      const cells = [
        extensionResult.extension,
        extensionResult.hits,
        extensionResult.uniqueRepos
      ]
      fileContents += `${cells.join(' | ')}\n`
    }
  }

  fileContents += '_Generated by a tool_'

  core.debug(fileContents)

  if (!whatIf) {
    fs.writeFileSync(outputPath, fileContents)
  }
}
