name: Harvest

# Controls when the action will run. 
on:
  workflow_dispatch:

jobs:
  harvest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        name: Run a multi-line script
        with:
          githubToken: ${{ github.token }}
          candidatesFile: ./candidates.json
