name: Harvest

# Controls when the action will run. 
on:
  workflow_dispatch:

jobs:
  harvest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        name: Run a multi-line script
        with:
          githubToken: ${{ secrets.MY_TOKEN }}
          candidatesFile: ./candidates.json

      - uses: EndBug/add-and-commit@2d77fa2c79bc4ea3abc933ecf12c270a5dc536b2
        with:
          message: "Updating extensions table"
          add: extensions.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
